require("options")
vim.cmd('source ~/.config/nvim/plug.vim')
require("layout")
require("navigate")
require("edit")
require("lang")
vim.cmd('source ~/.config/nvim/coc.vim')
-- require("coc")
-- require("lsp")
-- require("completion")
require("treesitter")
require("theme")
require("firenvimc")
